version: "3"
services:
   fluig-dbserver:
      image: docker.fluig.com/fluig/mysql:latest
      command: --init-file /data/application/init.sql
      environment:
         - MYSQL_ROOT_PASSWORD=YuCBDOZnqE5vL
      volumes:
         - ./mysql:/var/lib/mysql
         - ./init.sql:/data/application/init.sql
      networks:
         - platform
networks:
   platform:
