version: "3"
services:
   fluig-dbserver:
      container_name: fluig-dbserver
      image: docker.fluig.com/fluig/mysql:latest
      environment:
         - MYSQL_ROOT_PASSWORD=root123
      volumes:
         - ./data/mysql-master:/var/lib/mysql/
         - ./master.cnf:/etc/mysql/conf.d/master.cnf
      networks:
         - platform
   fluig-dbserver-slave:
      container_name: fluig-dbserver-slave
      image: docker.fluig.com/fluig/mysql:latest
      depends_on:
         - fluig-dbserver
      environment:
         - MYSQL_ROOT_PASSWORD=root123
      volumes:
         - ./data/mysql-slave:/var/lib/mysql/
         - ./slave.cnf:/etc/mysql/conf.d/slave.cnf
      networks:
         - platform
   fluig-dbserver-configure:
      image: docker.fluig.com/fluig/mysql:latest
      depends_on:
         - fluig-dbserver
         - fluig-dbserver-slave
      environment:
         - MYSQL_ROOT_PASSWORD=root123
         - MYSQL_SLAVE_PASSWORD=root123
         - MYSQL_MASTER_PASSWORD=root123
         - MYSQL_REPLICATION_USER=repl
         - MYSQL_REPLICATION_PASSWORD=repl
         - MYSQL_MASTER_HOSTNAME=fluig-dbserver
         - MYSQL_SLAVE_HOSTNAME=fluig-dbserver-slave
      volumes:
         - ./enable_slave.sh:/tmp/enable_slave.sh
         - ./init.sql:/tmp/init.sql
      command: /bin/bash -x /tmp/enable_slave.sh
      networks:
         - platform
networks:
   platform:
