version: "3"
services:
  discovery-application:
    image: platform/fluig-discovery:local
    environment:
      - FLUIG_URL=http://fluig-application:8080
      - FLUIG_HOST_URL_ADDRESS=http://fluig.local:8080
      - FLUIG_DISCOVERY_URL=http://discovery-application:8080
      - FLUIG_SERVICE_BASE_URL=http://discovery-application:8080
      # database configuration
      - FLUIG_DATABASE_USER=fluig
      - FLUIG_DATABASE_PASSWORD=OLyVu1gIwWmEr
      - FLUIG_DATABASE_URL=jdbc:mysql://fluig-dbserver:3306/fluig_discovery?useSSL=false&useLegacyDatetimeCode=false
      - FLUIG_DATABASE_DRIVER=com.mysql.jdbc.Driver
      - FLUIG_DATABASE_USER_RO=fluig
      - FLUIG_DATABASE_PASSWORD_RO=OLyVu1gIwWmEr
      - FLUIG_DATABASE_URL_RO=jdbc:mysql://fluig-dbserver:3306/fluig_discovery?useSSL=false&useLegacyDatetimeCode=false
      # Autenticacao
      - fluig.resource.jwk-enabled=true
      - volume=./volume
    networks:
      - platform
    extra_hosts:
      - "fluig.local:IP_ADDR"
      - "wcm.fluig.local:IP_ADDR"
      - "teste.fluig.local:IP_ADDR"
      - "javanei.fluig.local:IP_ADDR"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    depends_on:
      - artemis-server
  comm-application:
    image: platform/fluig-comm:local
    environment:
      - FLUIG_URL=http://fluig-application:8080
      - FLUIG_HOST_URL_ADDRESS=http://fluig.local:8080
      - FLUIG_DISCOVERY_URL=http://discovery-application:8080
      - FLUIG_SERVICE_BASE_URL=http://comm-application:8080
      # database configuration
      - FLUIG_DATABASE_USER=fluig
      - FLUIG_DATABASE_PASSWORD=OLyVu1gIwWmEr
      - FLUIG_DATABASE_URL=jdbc:mysql://fluig-dbserver:3306/fluig_comm?useSSL=false&useLegacyDatetimeCode=false
      - FLUIG_DATABASE_DRIVER=com.mysql.jdbc.Driver
      - FLUIG_DATABASE_USER_RO=fluig
      - FLUIG_DATABASE_PASSWORD_RO=OLyVu1gIwWmEr
      - FLUIG_DATABASE_URL_RO=jdbc:mysql://fluig-dbserver:3306/fluig_comm?useSSL=false&useLegacyDatetimeCode=false
      # Autenticacao
      - fluig.resource.jwk-enabled=true
      - volume=./volume
    networks:
      - platform
    extra_hosts:
      - "fluig.local:IP_ADDR"
      - "wcm.fluig.local:IP_ADDR"
      - "teste.fluig.local:IP_ADDR"
      - "javanei.fluig.local:IP_ADDR"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    depends_on:
      - artemis-server
  i18n-application:
    image: platform/fluig-i18n:local
    environment:
      - FLUIG_URL=http://fluig-application:8080
      - FLUIG_HOST_URL_ADDRESS=http://fluig.local:8080
      - FLUIG_DISCOVERY_URL=http://discovery-application:8080
      - FLUIG_SERVICE_BASE_URL=http://i18n-application:8080
      # database configuration
      - FLUIG_DATABASE_USER=fluig
      - FLUIG_DATABASE_PASSWORD=OLyVu1gIwWmEr
      - FLUIG_DATABASE_URL=jdbc:mysql://fluig-dbserver:3306/fluig_i18n?useSSL=false&useLegacyDatetimeCode=false
      - FLUIG_DATABASE_DRIVER=com.mysql.jdbc.Driver
      - FLUIG_DATABASE_USER_RO=fluig
      - FLUIG_DATABASE_PASSWORD_RO=OLyVu1gIwWmEr
      - FLUIG_DATABASE_URL_RO=jdbc:mysql://fluig-dbserver:3306/fluig_i18n?useSSL=false&useLegacyDatetimeCode=false
      # Autenticacao
      - fluig.resource.jwk-enabled=true
      - volume=./volume
    networks:
      - platform
    extra_hosts:
      - "fluig.local:IP_ADDR"
      - "wcm.fluig.local:IP_ADDR"
      - "teste.fluig.local:IP_ADDR"
      - "javanei.fluig.local:IP_ADDR"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    depends_on:
      - artemis-server
  comments-application:
    image: platform/fluig-comments:local
    environment:
      - FLUIG_URL=http://fluig-comments:8080
      - FLUIG_HOST_URL_ADDRESS=http://fluig.local:8080
      - FLUIG_DISCOVERY_URL=http://discovery-application:8080
      - FLUIG_SERVICE_BASE_URL=http://comments-application:8080
      # database configuration
      - FLUIG_DATABASE_USER=fluig
      - FLUIG_DATABASE_PASSWORD=OLyVu1gIwWmEr
      - FLUIG_DATABASE_URL=jdbc:mysql://fluig-dbserver:3306/fluig_comments?useSSL=false&useLegacyDatetimeCode=false
      - FLUIG_DATABASE_DRIVER=com.mysql.jdbc.Driver
      - FLUIG_DATABASE_USER_RO=fluig
      - FLUIG_DATABASE_PASSWORD_RO=OLyVu1gIwWmEr
      - FLUIG_DATABASE_URL_RO=jdbc:mysql://fluig-dbserver:3306/fluig_comments?useSSL=false&useLegacyDatetimeCode=false
      # Autenticacao
      - fluig.resource.jwk-enabled=true
      - volume=./volume
    networks:
      - platform
    extra_hosts:
      - "fluig.local:IP_ADDR"
      - "wcm.fluig.local:IP_ADDR"
      - "teste.fluig.local:IP_ADDR"
      - "javanei.fluig.local:IP_ADDR"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
  storage-application:
    image: platform/fluig-storage:local
    environment:
      - FLUIG_URL=http://fluig-storage:8080
      - FLUIG_HOST_URL_ADDRESS=http://fluig.local:8080
      - FLUIG_DISCOVERY_URL=http://discovery-application:8080
      - FLUIG_SERVICE_BASE_URL=http://storage-application:8080
      # database configuration
      - FLUIG_DATABASE_USER=fluig
      - FLUIG_DATABASE_PASSWORD=OLyVu1gIwWmEr
      - FLUIG_DATABASE_URL=jdbc:mysql://fluig-dbserver:3306/fluig_storage?useSSL=false&useLegacyDatetimeCode=false
      - FLUIG_DATABASE_DRIVER=com.mysql.jdbc.Driver
      - FLUIG_DATABASE_USER_RO=fluig
      - FLUIG_DATABASE_PASSWORD_RO=OLyVu1gIwWmEr
      - FLUIG_DATABASE_URL_RO=jdbc:mysql://fluig-dbserver:3306/fluig_storage?useSSL=false&useLegacyDatetimeCode=false
      # Autenticacao
      - fluig.resource.jwk-enabled=true
      - volume=./volume
    networks:
      - platform
    extra_hosts:
      - "fluig.local:IP_ADDR"
      - "wcm.fluig.local:IP_ADDR"
      - "teste.fluig.local:IP_ADDR"
      - "javanei.fluig.local:IP_ADDR"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
  scheduling-application:
    image: platform/fluig-scheduling:local
    environment:
      - FLUIG_URL=http://fluig-scheduling:8080
      - FLUIG_HOST_URL_ADDRESS=http://fluig.local:8080
      - FLUIG_DISCOVERY_URL=http://discovery-application:8080
      - FLUIG_SERVICE_BASE_URL=http://scheduling-application:8080
      # database configuration
      - FLUIG_DATABASE_USER=fluig
      - FLUIG_DATABASE_PASSWORD=OLyVu1gIwWmEr
      - FLUIG_DATABASE_URL=jdbc:mysql://fluig-dbserver:3306/fluig_scheduling?useSSL=false&useLegacyDatetimeCode=false
      - FLUIG_DATABASE_DRIVER=com.mysql.jdbc.Driver
      - FLUIG_DATABASE_USER_RO=fluig
      - FLUIG_DATABASE_PASSWORD_RO=OLyVu1gIwWmEr
      - FLUIG_DATABASE_URL_RO=jdbc:mysql://fluig-dbserver:3306/fluig_scheduling?useSSL=false&useLegacyDatetimeCode=false
      # Autenticacao
      - fluig.resource.jwk-enabled=true
      - volume=./volume
    networks:
      - platform
    extra_hosts:
      - "fluig.local:IP_ADDR"
      - "wcm.fluig.local:IP_ADDR"
      - "teste.fluig.local:IP_ADDR"
      - "javanei.fluig.local:IP_ADDR"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
  fluig-application:
    image: platform/fluig:local
    ports:
      - 8787:8787
    environment:
      # database configuration
      - FLUIG_DATABASE_SERVER=fluig-dbserver
      - FLUIG_DATABASE_PORT=3306
      - FLUIG_DATABASE_USER=fluig
      - FLUIG_DATABASE_PASSWORD=OLyVu1gIwWmEr
      - FLUIG_DATABASE_NAME=fluig
      # platform configuration
      - FLUIG_JMS_PASSWORD=platform
      - FLUIG_HOST_ADDRESS_PUBLIC=fluig-application
      - IDENTITY_URL=https://app.customerfi.com
      - FLUIG_HOST_URL_ADDRESS=http://fluig.local:8080
      - FLUIG_DISCOVERY_URL=http://discovery-application:8080
      # fluig billing config
      - FLUIG_COLLECTOR_APP_NAME=fluig_app
      - FLUIG_COLLECTOR_APP_TOKEN=77717171
      - FLUIG_COLLECTOR_TYPE=LOG
      - COLLECTOR_SERVER_URL=http://collector-server:8080/billing/api/v1
    command:
      - --debug
    networks:
      - platform
    extra_hosts:
      - "fluig.local:IP_ADDR"
      - "wcm.fluig.local:IP_ADDR"
      - "teste.fluig.local:IP_ADDR"
      - "javanei.fluig.local:IP_ADDR"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./volume:/opt/volume
  lms-application:
    image: platform/lms:local
    #ports:
    #   - 9797:9797
    environment:
      # database configuration
      - LMS_DATABASE_SERVER=lms-dbserver
      - LMS_DATABASE_PORT=3306
      - LMS_DATABASE_USER=fluig
      - LMS_DATABASE_PASSWORD=OLyVu1gIwWmEr
      - LMS_DATABASE_NAME=lms
      # lms configuration
      - LMS_JMS_PASSWORD=platform
      - LMS_ENDPOINT=lms-application:8080
      - FLUIG_ENDPOINT=fluig-application:8080
      - FLUIG_URL=http://fluig-application:8080
      - FLUIG_DISCOVERY_URL=http://discovery-application:8080
      - LMS_HOST_ADDRESS_PUBLIC=lms-application
      - FLUIG_COLLECTOR_APP_NAME=lms_app
      - FLUIG_COLLECTOR_APP_TOKEN=12345678
      - FLUIG_COLLECTOR_TYPE=LOG
      - COLLECTOR_SERVER_URL=http://collector-server:8080/billing/api/v1
    #command:
    #   - --debug 9797
    networks:
      - platform
    extra_hosts:
      - "fluig.local:IP_ADDR"
      - "wcm.fluig.local:IP_ADDR"
      - "teste.fluig.local:IP_ADDR"
      - "javanei.fluig.local:IP_ADDR"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./volume:/opt/volume
  artemis-server:
    image: platform/artemis-demo:local
    ports:
      - 8161:8161
      - 61616:61616
      - 8160:8160
    environment:
      - ARTEMIS_USERNAME=admin
      - ARTEMIS_PASSWORD=admin
      - ENABLE_JMX=true
      - JMX_PORT=1199
      - JMX_RMI_PORT=1198
      - volume=./volume
    networks:
      - platform
    extra_hosts:
      - "fluig.local:IP_ADDR"
      - "wcm.fluig.local:IP_ADDR"
      - "teste.fluig.local:IP_ADDR"
      - "javanei.fluig.local:IP_ADDR"
  nginx:
    image: docker.fluig.com/platform/nginx:latest
    ports:
      - 8080:80
    networks:
      - platform
    extra_hosts:
      - "fluig.local:IP_ADDR"
      - "wcm.fluig.local:IP_ADDR"
      - "teste.fluig.local:IP_ADDR"
      - "javanei.fluig.local:IP_ADDR"
    depends_on:
      - comm-application
      - i18n-application
      - discovery-application
      - comments-application
      - storage-application
      - scheduling-application
      - fluig-application
      - lms-application
    volumes:
      - ./nginx:/etc/nginx/sites/http/
networks:
  platform:
