version: "3"
services:
  nginx:
    image: docker.fluig.com/platform/nginx:latest
    env_file:
      - ./public.env
      - ./private.env
    ports:
      - 8080:80
    networks:
      - platform
    depends_on:
      - i18n-application
      - discovery-application
      - maestro-application
      - accounts-application
      #- comments-application
      - storage-application
      #- scheduling-application
      - fluig-application
      - lms-application
      - boards-application
      #- tasks-application
    volumes:
      - ./nginx:/etc/nginx/sites/http/
