  fluig-application:
    #image: docker.fluig.com/platform/fluig:${fluigVersion}
    image: platform/fluig:local
    ports:
      - 8787:8787
    env_file:
      - ./public.env
      - ./private.env
    environment:
      # database configuration
      - FLUIG_DATABASE_SERVER=fluig-dbserver
      - FLUIG_DATABASE_SERVER_RO=fluig-dbserver
      - FLUIG_DATABASE_PORT=3306
      - FLUIG_DATABASE_NAME=fluig
      - FLUIG_DATABASE_URL=jdbc:mysql://fluig-dbserver:3306/fluig?useSSL=false&useLegacyDatetimeCode=false
      - FLUIG_DATABASE_URL_RO=jdbc:mysql://fluig-dbserver:3306/fluig?useSSL=false&useLegacyDatetimeCode=false
      # platform configuration
      - FLUIG_JMS_PASSWORD=platform
      - FLUIG_HOST_ADDRESS_PUBLIC=fluig-application
#    command:
#      - --debug
    networks:
      - platform
    depends_on:
      - i18n-application
      - discovery-application
      - maestro-application
      - accounts-application
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      # format is "<local folder or file>:<container folder or file>"
      - ./volume:/opt/volume
