  fluig-migration:
    image: platform/fluig-core-dbmigration:local
    environment:
      - FLUIG_DATABASE_USER=fluig
      - FLUIG_DATABASE_PASSWORD=fluig123
      - FLUIG_DATABASE_URL=jdbc:mysql://fluig-dbserver:3306/fluig?useSSL=false&useLegacyDatetimeCode=false
      - FLUIG_DATABASE_DRIVER=com.mysql.jdbc.Driver
    networks:
      - platform
