  i18n-application:
    #image: docker.fluig.com/platform/fluig-i18n:${i18nVersion}
    image: platform/fluig-i18n:local
    env_file:
      - ./public.env
      - ./private.env
    environment:
      - FLUIG_SERVICE_BASE_URL=http://i18n-application:8080
      # database configuration
      - FLUIG_DATABASE_URL=jdbc:mysql://fluig-dbserver:3306/fluig_i18n?useSSL=false&useLegacyDatetimeCode=false
      - FLUIG_DATABASE_DRIVER=com.mysql.jdbc.Driver
      - FLUIG_DATABASE_URL_RO=jdbc:mysql://fluig-dbserver-slave:3306/fluig_i18n?useSSL=false&useLegacyDatetimeCode=false
      # Autenticacao
      - accounts.resource.jwk-enabled=true
    networks:
      - platform
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
