  lms-migration:
    #image: docker.fluig.com/platform/lms/migration:${learningVersion}
    #image: platform/lms/migration:local
    image: docker.fluig.com/platform/lms/migration:0c0ea6a
    env_file:
      - ./public.env
      - ./private.env
    environment:
      # database configuration
      - LMS_DATABASE_SERVER=fluig-dbserver
      - LMS_DATABASE_PORT=3306
      - LMS_DATABASE_USER=fluig
      - LMS_DATABASE_PASSWORD=fluig123
      - LMS_DATABASE_NAME=lms
    networks:
      - platform
