  lms-application:
    #image: docker.fluig.com/platform/lms:${learningVersion}
    image: docker.fluig.com/platform/lms:0c0ea6a
    #image: platform/lms:local
    #ports:
    #   - 9797:9797
    env_file:
      - ./public.env
      - ./private.env
    environment:
      # database configuration
      - LMS_DATABASE_SERVER=fluig-dbserver
      - LMS_DATABASE_PORT=3306
      - LMS_DATABASE_USER=fluig
      - LMS_DATABASE_PASSWORD=fluig123
      - LMS_DATABASE_NAME=lms
      # lms configuration
      - LMS_JMS_PASSWORD=platform
      - LMS_ENDPOINT=lms-application:8080
      - LMS_HOST_ADDRESS_PUBLIC=lms-application
      - CLOUD_REPOSITORY=false
    restart: always
    networks:
      - platform
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./volume:/opt/volume
#    depends_on:
#      #- lms-migration
#      - learning-volume-update
#  learning-volume-update:
#    #image: docker.fluig.com/platform/lms/volume-update:${learningVersion}
#    image: platform/lms/volume-update:local
#    environment:
#      # database configuration
#      - LMS_DATABASE_SERVER=fluig-dbserver
#      - LMS_DATABASE_PORT=3306
#      - LMS_DATABASE_USER=fluig
#      - LMS_DATABASE_PASSWORD=fluig123
#      - LMS_DATABASE_NAME=lms
#    networks:
#      - platform
#    volumes:
#      - ./volume:/opt/volume
