  manager-application:
    image: docker.fluig.com/platform/manager:5b53ecd
    #image: platform/manager:local
    env_file:
      - ./public.env
      - ./private.env
    ports:
      - 8789:8789
#    environment:
      # Fluig config
    networks:
      - platform
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
