  scheduling-migration:
    #image: platform/fluig-scheduling-dbmigration:local
    image: docker.fluig.com/platform/fluig-scheduling-dbmigration:${schedulingVersion}
    env_file:
      - ./public.env
      - ./private.env
    environment:
      - FLUIG_DATABASE_URL=jdbc:mysql://fluig-dbserver:3306/fluig_scheduling?useSSL=false&useLegacyDatetimeCode=false
      - FLUIG_DATABASE_DRIVER=com.mysql.jdbc.Driver
    networks:
      - platform
