  storage-application:
    image: docker.fluig.com/platform/fluig-storage:${storageVersion}
    #image: platform/fluig-storage:local
    env_file:
      - ./public.env
      - ./private.env
    environment:
      - FLUIG_SERVICE_BASE_URL=http://storage-application:8080
      # database configuration
      - FLUIG_DATABASE_URL=jdbc:mysql://fluig-dbserver:3306/fluig_storage?useSSL=false&useLegacyDatetimeCode=false
      - FLUIG_DATABASE_DRIVER=com.mysql.jdbc.Driver
      - FLUIG_DATABASE_URL_RO=jdbc:mysql://fluig-dbserver:3306/fluig_storage?useSSL=false&useLegacyDatetimeCode=false
      # Autenticacao
      - accounts.resource.jwk-enabled=true
    networks:
      - platform
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
