version: "3"
services:
  nginx:
    image: docker.fluig.com/platform/nginx:latest
    # map local port 8080 to 80 into the nginx container
    ports:
      - 8080:80
    networks:
      - platform
    depends_on:
      - i18n-application
      - discovery-application
      - fluig-application
    volumes:
      - ./nginx:/etc/nginx/sites/http/
