version: "3"
services:
  discovery-application:
    #image: docker.fluig.com/platform/fluig-discovery:${discoveryVersion}
    image: platform/fluig-discovery:local
    environment:
      - FLUIG_URL=http://fluig-application:8080
      - FLUIG_HOST_URL_ADDRESS=http://fluig.local:8080
      - FLUIG_DISCOVERY_URL=http://discovery-application:8080
      - FLUIG_SERVICE_BASE_URL=http://discovery-application:8080
      # database configuration
      - FLUIG_DATABASE_USER=fluig
      - FLUIG_DATABASE_PASSWORD=OLyVu1gIwWmEr
      - FLUIG_DATABASE_URL=jdbc:mysql://fluig-dbserver:3306/fluig_discovery?useSSL=false&useLegacyDatetimeCode=false
      - FLUIG_DATABASE_DRIVER=com.mysql.jdbc.Driver
      - FLUIG_DATABASE_USER_RO=fluig
      - FLUIG_DATABASE_PASSWORD_RO=OLyVu1gIwWmEr
      - FLUIG_DATABASE_URL_RO=jdbc:mysql://fluig-dbserver:3306/fluig_discovery?useSSL=false&useLegacyDatetimeCode=false
      # Autenticacao
      - fluig.resource.jwk-enabled=true
    networks:
      - platform
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
  i18n-application:
    #image: docker.fluig.com/platform/fluig-i18n:${i18nVersion}
    image: platform/fluig-i18n:local
    environment:
      - FLUIG_URL=http://fluig-application:8080
      - FLUIG_HOST_URL_ADDRESS=http://fluig.local:8080
      - FLUIG_DISCOVERY_URL=http://discovery-application:8080
      - FLUIG_SERVICE_BASE_URL=http://i18n-application:8080
      # database configuration
      - FLUIG_DATABASE_USER=fluig
      - FLUIG_DATABASE_PASSWORD=OLyVu1gIwWmEr
      - FLUIG_DATABASE_URL=jdbc:mysql://fluig-dbserver:3306/fluig_i18n?useSSL=false&useLegacyDatetimeCode=false
      - FLUIG_DATABASE_DRIVER=com.mysql.jdbc.Driver
      - FLUIG_DATABASE_USER_RO=fluig
      - FLUIG_DATABASE_PASSWORD_RO=OLyVu1gIwWmEr
      - FLUIG_DATABASE_URL_RO=jdbc:mysql://fluig-dbserver:3306/fluig_i18n?useSSL=false&useLegacyDatetimeCode=false
      # Autenticacao
      - fluig.resource.jwk-enabled=true
    networks:
      - platform
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
  fluig-application:
    #image: docker.fluig.com/platform/fluig:${fluigVersion}
    image: platform/fluig:local
    ports:
      - 8787:8787
    environment:
      # database configuration
      - FLUIG_DATABASE_SERVER=fluig-dbserver
      - FLUIG_DATABASE_PORT=3306
      - FLUIG_DATABASE_USER=fluig
      - FLUIG_DATABASE_PASSWORD=OLyVu1gIwWmEr
      - FLUIG_DATABASE_NAME=fluig
      # platform configuration
      - FLUIG_JMS_PASSWORD=platform
      - FLUIG_HOST_ADDRESS_PUBLIC=fluig-application
      - IDENTITY_URL=https://app.customerfi.com
      - FLUIG_HOST_URL_ADDRESS=http://fluig.local:8080
      - FLUIG_DISCOVERY_URL=http://discovery-application:8080
      # cloud config
      - DOMAIN_NAME=${DOMAIN_NAME:-XXX}
      - CLOUD_PROVIDER=${CLOUD_PROVIDER:-NONE}
      # aws config
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-XXX}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-XXX}
      - AWS_HOST_ZONE_ID=${AWS_HOST_ZONE_ID:-XXX}
    command:
      - --debug
    networks:
      - platform
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./volume:/opt/volume
  lms-application:
    #image: docker.fluig.com/platform/lms:${learningVersion}
    image: platform/lms:local
    #ports:
    #   - 9797:9797
    environment:
      # database configuration
      - LMS_DATABASE_SERVER=lms-dbserver
      - LMS_DATABASE_PORT=3306
      - LMS_DATABASE_USER=fluig
      - LMS_DATABASE_PASSWORD=OLyVu1gIwWmEr
      - LMS_DATABASE_NAME=lms
      # lms configuration
      - LMS_JMS_PASSWORD=platform
      - LMS_ENDPOINT=lms-application:8080
      - FLUIG_ENDPOINT=fluig-application:8080
      - FLUIG_URL=http://fluig-application:8080
      - FLUIG_DISCOVERY_URL=http://discovery-application:8080
      - LMS_HOST_ADDRESS_PUBLIC=lms-application
    #command:
    #   - --debug 9797
    networks:
      - platform
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./volume:/opt/volume
  nginx:
    image: docker.fluig.com/platform/nginx:latest
    ports:
      - 8080:80
    networks:
      - platform
    depends_on:
      - i18n-application
      - discovery-application
      - fluig-application
      - lms-application
    volumes:
      - ./nginx:/etc/nginx/sites/http/
networks:
  platform:
