version: "3"
services:
  fluig-dbserver:
    image: docker.fluig.com/fluig/mysql:latest
    command: --init-file /data/application/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=YuCBDOZnqE5vL
      - volume=./volume
    volumes:
      - mysql-fluig:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    networks:
      - platform
  lms-dbserver:
    image: docker.fluig.com/fluig/mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=YuCBDOZnqE5vL
      - MYSQL_USER=fluig
      - MYSQL_PASSWORD=OLyVu1gIwWmEr
      - MYSQL_DATABASE=lms
      - volume=./volume
    volumes:
      - mysql-lms:/var/lib/mysql
    networks:
      - platform
networks:
  platform:
volumes:
  mysql-fluig:
  mysql-lms:
